#ifndef UE4SS_SDK_BP_Block21_RemoveMagInsertMagChamber_Driver_HPP
#define UE4SS_SDK_BP_Block21_RemoveMagInsertMagChamber_Driver_HPP

class UBP_Block21_RemoveMagInsertMagChamber_Driver_C : public UBP_WeaponReloadBase_Handgun_RemoveMagazineInsertMagazineChamber_Driver_C
{
}; // Size: 0x90

#endif
