// BlueprintGeneratedClass HTZ_Military_HotSpotUnderground_Character_Encounter_Child.HTZ_Military_HotSpotUnderground_Character_Encounter_Child_C
// Size: 0x588 (Inherited: 0x588)
struct UHTZ_Military_HotSpotUnderground_Character_Encounter_Child_C : UBP_EncounterHordeBase_C {
};

