// BlueprintGeneratedClass MTZ_Settlement_Big_City_Radiation_NPC_Encounter_LPC_Child.MTZ_Settlement_Big_City_Radiation_NPC_Encounter_LPC_Child_C
// Size: 0x460 (Inherited: 0x460)
struct UMTZ_Settlement_Big_City_Radiation_NPC_Encounter_LPC_Child_C : UEncounterSpawnCharacters {
};

