#ifndef UE4SS_SDK_TutorialInjury_ApplyBandagesOrDisinfect_HPP
#define UE4SS_SDK_TutorialInjury_ApplyBandagesOrDisinfect_HPP

class UTutorialInjury_ApplyBandagesOrDisinfect_C : public UPrisonerBodyConditionTreatInteraction_ApplyBandagesOrDisinfect
{
}; // Size: 0x128

#endif
