#ifndef UE4SS_SDK_UI_ModularTooltipElement_ValueWithModifier_Large_HPP
#define UE4SS_SDK_UI_ModularTooltipElement_ValueWithModifier_Large_HPP

class UUI_ModularTooltipElement_ValueWithModifier_Large_C : public UModularTooltipElement_ValueWithModifier
{
}; // Size: 0x320

#endif
